// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjHQ7DJwjc9fMVzcm7HUXhPI_t4g0if0',
    appId: '1:958581258711:web:db26b6dbc052a28a4fb392',
    messagingSenderId: '958581258711',
    projectId: 'proj-app-movil',
    authDomain: 'proj-app-movil.firebaseapp.com',
    storageBucket: 'proj-app-movil.appspot.com',
    measurementId: 'G-83J21MKCZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOqtCH8MWyrEvdKyijmeB8bJu9xqjUjY',
    appId: '1:958581258711:android:7e07750c007172504fb392',
    messagingSenderId: '958581258711',
    projectId: 'proj-app-movil',
    storageBucket: 'proj-app-movil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMdLPf22agpc_xVRKEnXYT3KUEc7Gp_Y',
    appId: '1:958581258711:ios:9ff8ac224d79720b4fb392',
    messagingSenderId: '958581258711',
    projectId: 'proj-app-movil',
    storageBucket: 'proj-app-movil.appspot.com',
    iosClientId: '958581258711-j5pols35depl18csi9dat6g1s1u42dgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projAppRoberto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMdLPf22agpc_xVRKEnXYT3KUEc7Gp_Y',
    appId: '1:958581258711:ios:9ff8ac224d79720b4fb392',
    messagingSenderId: '958581258711',
    projectId: 'proj-app-movil',
    storageBucket: 'proj-app-movil.appspot.com',
    iosClientId: '958581258711-j5pols35depl18csi9dat6g1s1u42dgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projAppRoberto',
  );
}
